### ISSUE TITLE
Declaration of string parameters in Simulator

### ISSUE THREAD

**Issue by MassimoCimmino** [lbl-srg/BuildingsPy#102]
There seems to be an issue with how BuildingsPy handles the declaration of string parameters.

For example, calling the model in Buildings.Fluid.Examples.SimpleHouse but changing the weather data file like so:
```
import buildingspy.simulate.Simulator as si

def main():
    model = 'Buildings.Fluid.Examples.SimpleHouse'
    s = si.Simulator(model, 'dymola')
    weatherFile = 'modelica://Buildings/Resources/weatherdata/USA_CA_San.Francisco.Intl.AP.724940_TMY3.mos'
    s.addParameters({'weaDat.filNam' : weatherFile})
    s.setTimeOut(60)
    
    try:
        s.simulate()
    except:
        with open('simulator.log') as f:
            print f.read()
    
# Main function
if __name__ == '__main__':
    main()
```
leads to a failed simulation with the simulation log:
```
RunScript("d:/program files (x86)/dymola 2017/insert/dymola.mos", true);
 = true
 = true
RunScript("C:/Users/massi/AppData/Roaming/Dynasim/setup.mos", true);
 = true
RunScript("c:\\users\\massi\\appdata\\local\\temp\\tmp-simulator-massi-mxj0ct\\pyHeatPump\\run.mos");

// File autogenerated by _get_dymola_commands
// Do not edit.
cd("c:\users\massi\appdata\local\temp\tmp-simulator-massi-mxj0ct\pyHeatPump");
C:/users/massi/appdata/local/temp/tmp-simulator-massi-mxj0ct/pyHeatPump
 = true
Modelica.Utilities.Files.remove("simulator.log");
openModel("package.mo");
 = true
OutputCPUtime:=true;
modelInstance="Buildings.Fluid.Examples.SimpleHouse(weaDat.filNam='modelica://Buildings/Resources/weatherdata/USA_CA_San.Francisco.Intl.AP.724940_TMY3.mos')";
Declaring variable: String modelInstance ;

simulateModel(modelInstance, startTime=0, stopTime=1, method="radau", tolerance=1e-06, resultFile="SimpleHouse");
 = false
savelog("simulator.log");
```

The problem comes from the use of `repr(arg)` when declaring string parameters, which produces single quotes (') instead of double quotes (").
The following line:
`modelInstance="Buildings.Fluid.Examples.SimpleHouse(weaDat.filNam='modelica://Buildings/Resources/weatherdata/USA_CA_San.Francisco.Intl.AP.724940_TMY3.mos')";`
Should properly be:
`modelInstance="Buildings.Fluid.Examples.SimpleHouse(weaDat.filNam=\"modelica://Buildings/Resources/weatherdata/USA_CA_San.Francisco.Intl.AP.724940_TMY3.mos\")";`

Changing the check for strings in Simulator._declare_parameters.to_modelica seems to fix this issue.
Current implementation:
```
if isinstance(arg, str):
    return repr(arg)
```
Modified implementation:
```
if isinstance(arg, str):
    return '\\"' + arg + '\\"'
```

**Comment by mwetter** [comment]
@MassimoCimmino 
Thanks. Can you try again with the latest version from the `master` and close this issue if a20520e
 fixes it.

**Comment by MassimoCimmino** [comment]
@mwetter 
This seems to have solved the issue. However, in the current version of the master, care should be taken when defining the string parameters due to the use of builtins.str in Simulator.py.

The following example runs without any issues:

```
from builtins import str
import buildingspy.simulate.Simulator as si

def main():
    model = 'Buildings.Fluid.Examples.SimpleHouse'
    s = si.Simulator(model, 'dymola')
    weatherFile = str('modelica://Buildings/Resources/weatherdata/USA_CA_San.Francisco.Intl.AP.724940_TMY3.mos')
    s.addParameters({'weaDat.filNam' : weatherFile})
    s.setTimeOut(60)
    s.simulate()
    with open('simulator.log') as f:
        print f.read()
    
# Main function
if __name__ == '__main__':
    main()
```

**Comment by mwetter** [comment]
@MassimoCimmino Can you please say what "care should be taken"? Is there any test we need to build into the code, or advise for the user to add to the documentation?

**Comment by MassimoCimmino** [comment]
In my example, the code fails if the parameter is declared as:
```
weatherFile = 'modelica://Buildings/Resources/weatherdata/USA_CA_San.Francisco.Intl.AP.724940_TMY3.mos'
```
because Simulator.py has the `from builtins import str` import statement, which in turn makes the following check in Simulator._declare_parameters return false:
```
if isinstance(arg, str)
```

To circumvent this issue, I have imported str from the builtins module and have declared the string variable using this same str function:

```
from builtins import str
(...)
weatherFile = str('modelica://Buildings/Resources/weatherdata/USA_CA_San.Francisco.Intl.AP.724940_TMY3.mos')
```

**Comment by thorade** [comment]
Sorry for breaking your workflow. The line `from builtins import str` was introduced with PR #100, as part of making BuildingsPy compatible with Python 2.7 and Python 3.5 (issue #94). My impression is that string handling is the most complicated part of writing code that runs on Py2 and Py3, on Windows and Linux and OSX. 
Your fix is (as far as I know) the cleanest solution to write Py2 and 3 compatible code, but it requires changes on the user side. The alternative would be to add a Python version detection in BuildingsPy and handle the incoming argument depending on the Python version.

**Comment by MassimoCimmino** [comment]
The problem here is that `builtins.str` and `str` are not considered the same type, so the line `if isinstance(arg, str)` will fail anytime the calling script and the buildingspy method don't use the same type of string.

The quick and easy fix in this particular case could be to check the type using `type().__name__` instead of using `isinstance()`. Since `type(builtins.str()).__name__` returns `newstr` and `type(str()).__name__` returns `str`, the check can be replaced by:
```
if type(arg).__name__ in ['str', 'newstr']:
(...)
```
I was able to call the simulator without using the `builtins` module this way. This worked on Python 2.7 running Windows.

**Comment by thorade** [comment]
I think `isinstance` allows to specify two types like
```python
isinstance(arg, (str,newstr))
```
http://stackoverflow.com/a/33311330/874701
Would that help?

**Comment by MassimoCimmino** [comment]
Following a comment from @thorade, I have found that strings can be tested against the superclass `basestring`:
```
if isinstance(arg, basestring):
```
I have tested this [on my fork](/MassimoCimmino/BuildingsPy/tree/issue102_stringParameters) and it works with both inputs of type `str` and `builtins.str`.
Would this create any problems with Python 3 compatibility (issue #94)?

**Comment by thorade** [comment]
I deleted my previous comment, because it would not have worked on Python3. Python3 does not know newstr or basestring. Still, comparing against basestring is good, because it fixes your error and then on Python3 one could add
```
try:
  basestring
except NameError:
  basestring = str
```
as shown here: http://stackoverflow.com/a/22679982/874701

**Comment by MassimoCimmino** [comment]
This doesn't seem to create any issues in Python 2 when placed in the header of the script, like so:
```
from __future__ import absolute_import
from __future__ import division
from __future__ import print_function
#from __future__ import unicode_literals

from builtins import str
from builtins import range
from builtins import object
try:
    basestring
except NameError:
    basestring = str
```
I believe this finally fixes the issue.
