### ISSUE TITLE
refactor.py also finds commented types

### ISSUE THREAD

**Issue by thorade** [lbl-srg/BuildingsPy#104]
refactor.py finds type declarations in comments and adds them to the package.order
```modelica
within BuildingSystems.HAM.ConvectiveHeatTransfer;
package Gaps "Functions for convective heat transfer within gaps or parallel surfaces"
  extends Modelica.Icons.VariantsPackage;
  // type Gas = enumeration(air, argon, krypton);
  // Gas gas = Gas.air  "gas: air, argon or krypton";

end Gaps;
```
Also see https://github.com/UdK-VPT/BuildingSystems/issues/9

These comments will be deleted some time soon in our library, 
not sure whether it is worth changing BuildingsPy,
feel free to just close as won't fix.

**Comment by mwetter** [comment]
Please make a pull request if you want to change it. The refactor script does not cover all corner cases as this would require a complete parsing of the Modelica syntax

**Comment by thorade** [comment]
I'll close this for now and if I happen to run into the same error again I will re-open and send a pull request.
