### ISSUE TITLE
different FMI results 

### ISSUE THREAD

**Issue by Mathadon** [lbl-srg/BuildingsPy#115]
When running buildingspy 1.5.0 (pip version) I get output for the FMI unit tests:

```
*** Warning: Reference file IDEAS_Fluid_FMI_ExportContainers_Validation_FMUs_ThermalZoneSimpleAir3.txt has different FMU statistics for 'InitialUnknowns'.
*** Warning: Reference file IDEAS_Fluid_FMI_ExportContainers_Validation_FMUs_ThermalZoneSimpleAir3.txt has different FMU statistics for 'Outputs'.
```

should this happen?

**Comment by mwetter** [comment]
@Mathadon This probably happens because the `Annex60` reference results were generated with Dymola 2017, but you may use Dymola 2017FD01 in your tests. These produce different FMU statistics.

**Comment by Mathadon** [comment]
Actually I use dymola 2017 but let's wait and see what happens with a next release.
