### ISSUE TITLE
Error with wrong .mos file encoding (utf-8 instead of us-ascii)

### ISSUE THREAD

**Issue by dhblum** [lbl-srg/BuildingsPy#137]
I ran into an issue where a .mos file for a unit test example was encoded with charset=utf-8 (perhaps from the editor I used to edit it), and it triggered the following error in BuildingsPy when running unit tests:

"
Traceback (most recent call last):
  File "../bin/runUnitTests.py", line 142, in <module>
    n_pro = args.number_of_processors)
  File "../bin/runUnitTests.py", line 75, in _runUnitTests
    retVal = ut.run()
  File "/home/dhblum/git/BuildingsPy/buildingspy/development/regressiontest.py", line 2303, in run
    r = self._checkReferencePoints(ans)
  File "/home/dhblum/git/BuildingsPy/buildingspy/development/regressiontest.py", line 1637, in _checkReferencePoints
    y_tra=self._getTranslationStatistics(data, warnings, errors)
  File "/home/dhblum/git/BuildingsPy/buildingspy/development/regressiontest.py", line 964, in _getTranslationStatistics
    return of.get_model_statistics(fulFilNam, "dymola")
  File "/home/dhblum/git/BuildingsPy/buildingspy/io/outputfile.py", line 51, in get_model_statistics
    raise IOError("File {} does not exist".format(log_file));
IOError: <exception str() failed>
"

All other .mos files that successfully ran the tests were encoded with charset=us-ascii.  

This issue is to implement handling of files with utf-8 encoding.

**Comment by dhblum** [comment]
One other note is that the encoding of a file can be checked in Linux with:

$  file -bi <file>

**Comment by thorade** [comment]
Does that happen on Windows or Linux? What Python version?
Can you show the full script that reproduces the error?

Is the mos file part of a repository so that you could link to it?
Does the mos script contain non-ascii characters?
Is it Utf with or without BOM (byte order mark)?
As far as I know, ascii is identical to the first 128 characters in utf8, so as long as there are only ascii characters in the file, it should not matter whether you open it as ascii or utf8.

When on Windows, the most comfortable way for checking and converting encodings is probably using [Notepad++](https://notepad-plus-plus.org/).

**Comment by dhblum** [comment]
I'm sorry, I should have been more clear.

It happened on Linux.  Python 2.7.
The full command that caused the error is below.

With a bit more investigation, the problem occurs when the mos file is encoded with BOM, not necessarily that it is utf-8.  In line 720 of regressiontest.py (dat['TranslationLogFile'] = modNam + ".translation.log"), the log file name ends up having ï»¿ in front of it (can be seen in the Ubuntu Files viewer) , which gives issues when trying to read the file name later in the code.

In the end, removing the BOM from the mos file solves the problem.  You can reproduce the error by encoding any of the mos files with BOM.

You're right that Notepad++ is easiest for checking and converting encodings.

"
:$ python ../bin/runUnitTests.py -s IBPSA.Fluid.Actuators.Dampers
Regression tests are only run for the following package:
  IBPSA.Fluid.Actuators.Dampers
Using 3 of 8 processors to run unit tests.
Number of models   : 218
          blocks   : 101
          functions: 67
Generated 3 regression tests.

Traceback (most recent call last):
  File "../bin/runUnitTests.py", line 142, in <module>
    n_pro = args.number_of_processors)
  File "../bin/runUnitTests.py", line 75, in _runUnitTests
    retVal = ut.run()
  File "/home/dhblum/git/BuildingsPy/buildingspy/development/regressiontest.py", line 2299, in run
    r = self._checkReferencePoints(ans)
  File "/home/dhblum/git/BuildingsPy/buildingspy/development/regressiontest.py", line 1633, in _checkReferencePoints
    y_tra=self._getTranslationStatistics(data, warnings, errors)
  File "/home/dhblum/git/BuildingsPy/buildingspy/development/regressiontest.py", line 960, in _getTranslationStatistics
    return of.get_model_statistics(fulFilNam, "dymola")
  File "/home/dhblum/git/BuildingsPy/buildingspy/io/outputfile.py", line 52, in get_model_statistics
    raise IOError("File {} does not exist".format(log_file))
IOError: <exception str() failed>
"

**Comment by thorade** [comment]
And do you use the version from PyPi or the latest master? 
The master has some changes related to encodings etc

**Comment by dhblum** [comment]
The latest master.  I just ran a git fetch and git says my master is up to date.

**Comment by thorade** [comment]
It seems this is related to line 714 of regressiontest.py:
If I replace re.search by re.match, it will also work when the mos script contains a BOM, but I am not sure whether that could produce new failures!?
Another solution that worked for me was to match only at string beginning using a caret^
