### ISSUE TITLE
option to skip .copiedFiles in regression test

### ISSUE THREAD

**Issue by thorade** [lbl-srg/BuildingsPy#143]
The file `.copiedFiles.txt` contains a list of all files that were copied to a library from the IBPSA library. Assuming the copied models work just fine, I sometimes would like to run only the tests that were added in the extending library, to save some time.
If that sounds reasonable, I can implement it and submit a Pull Request in ~3 weeks.

**Comment by mwetter** [comment]
Is this (optional setting I assume) saving much time? For `Buildings`, the majority of the testing time comes from examples/validations of `Buildings` that are not in `IBPSA`. Also, as tests are run on travis and this merge is not done that frequent, it is for us not an issue.

**Comment by thorade** [comment]
For us, it is ~350 quick tests from IBPSA and ~70 slower tests that we added. I would use the option only when testing on my own computer.

**Comment by mwetter** [comment]
Then such an option makes sense for you. Just make sure the default run that checks all models is not changed.

**Comment by thorade** [comment]
There seems to be everything prepared for this feature: the function `_includeFile` is called for every mos script to test whether it should be included, it compares the mos script name against the global list `self._excludeMos`. I added a function that adds the copied files to that exclude list, but they are still included in the regression tests, so either my list format is wrong, or the function `_includeFile` does not work as I expected.

**Comment by thorade** [comment]
I changed the `_includeFile` function
https://github.com/lbl-srg/BuildingsPy/commits/issue143_excludeCopied
and the scripts from the `_excludeMos` list now seem to be excluded.

But then the regression tests fail with `KeyError: 'ResultFile'`
