### ISSUE TITLE
Q: load two libraries

### ISSUE THREAD

**Issue by thorade** [lbl-srg/BuildingsPy#150]
The BuildingSystems library depends on a second library, the netCDF Reader library. Without this dependency many of the example .mos scripts do not run. What is the "correct" way to load such a dependency? I am not aware of a way to do it via BuildingsPy. Is there a way to pass arbitrary commands to the simulation tool before running the unit tests?
I could load the dependency from the mos script, but when investigating this option, I noticed that the mos scripts also do NOT load the main library. This means, the mos scripts in their current form cannot be run directly from the command prompt using `dymola ./example.mos` or similar. Is that for performance reasons?
Any comments?

**Comment by mwetter** [comment]
You should be able to point the environment variable `MODELICAPATH` to your library before starting BuildingsPy. This should get inherited by all processes.

**Comment by thorade** [comment]
Thanks, the following code worked for me:
```python
moLibsDir = "C:/Users/mthorade/Documents/Dymola"
moLib = "modelica-ibpsa/IBPSA"
moLibPath = os.path.join(moLibsDir, moLib)
ncdLibPath = os.path.join(moLibsDir, "netCDF-DataReader/NcDataReader2")

def addDirToModelicaPath(DirPath):
    if os.environ.get('MODELICAPATH') is None:
        os.environ['MODELICAPATH'] = ';'.join([DirPath])
    elif DirPath in os.environ['MODELICAPATH']:
        print("Already on the MODELICAPATH, not doing anything")
    else:
        os.environ['MODELICAPATH'] = ';'.join([DirPath, os.environ['MODELICAPATH']])

addDirToModelicaPath(ncdLibPath)
# call buildingspy as usually after this line
```
Is that something that should be added to BuildingsPy? Where?
If not, this issue can be closed.

**Comment by mwetter** [comment]
I suggest to set up the environment variables outside of BuildingsPy, as too much smarts in changing environment variables may confuse users when things work, don't work, or work differently from what they expect.

**Comment by thorade** [comment]
Good
