### ISSUE TITLE
reference results file format

### ISSUE THREAD

**Issue by thorade** [lbl-srg/BuildingsPy#162]
This is just an idea: 
Currently the reference results are stored in a .txt file with key=value syntax, one entry per line. 
Using a different format could make processing the files even easier. My suggestion would be to store the real results as a plain/pure csv file, such that csv-compare, Excel, and github can diretly open it without any conversion. 
https://github.com/modelica-tools/csv-compare
https://github.com/blog/1601-see-your-csvs

Everything else (the translation statistics, last-generated date, etc) can be stored in a json file with the identical name, except the extension, such that it can be opened directly in tools like this:
http://www.jsoneditoronline.org/?url=https%3A%2F%2Fraw.githubusercontent.com%2Fjosdejong%2Fjsoneditor%2Fmaster%2Ftest%2Flargefile.json

Would that make sense?

**Comment by mwetter** [comment]
csv would be less compact as we store also some parameters without storing the whole time series. This saves space and allows to immediately see what is a parameter.

You can run `./Scripts/JModelica/buildingspy_to_csv.py` to get the csv file if needed.

**Comment by thorade** [comment]
That should be sufficient, thanks!
