### ISSUE TITLE
__Dymola_experimentSetupOutput(events=false) flag ignored

### ISSUE THREAD

**Issue by adbuerger** [lbl-srg/BuildingsPy#163]
I have a simulation that generates a lot of events, which causes the output file to become very big. So I usually deactivate the "Store variables at events"-flag in the output settings of Dymola, which works fine. If I store this setting in the .mo file, I can see an annotation

`__Dymola_experimentSetupOutput(events=false))`

However when running the simulation with buildingspy, it seems that this flag is being ignored, since the output file grows as if the flag hadn't been changed. Can you think of a reason why this happens and what can be done that this flag is being recognized?

**Comment by thorade** [comment]
BuildingsPy can set flags before running a simulation using the `addPreProcessingStatement` function:
http://simulationresearch.lbl.gov/modelica/buildingspy/simulate.html#buildingspy.simulate.Simulator.Simulator.addPreProcessingStatement

Issue #91 discusses to add the same option also for the regressiontests module.

But unfortunately this setting is not accessible as a flag:
https://stackoverflow.com/q/15292438/874701
You can get a [list of all flags](https://stackoverflow.com/q/17276571/874701) by entering `list()` in Dymolas Command Prompt.
You can copy the output to a text file, then it is nicer to read&search.

Maybe the answer from stackoverflow can be used to change that setting?

**Comment by mwetter** [comment]
I would be surprised if the annotation is ignored. You can test it by running
```
dymola someScript.mos
```
where `someScript.mos` runs your model. This is what BuildingsPy executes when running a simulation. Hence, the annotation `__Dymola_experimentSetupOutput(events=false))` should not be ignored.

**Comment by thorade** [comment]
Does .mo versus .mos make a difference?

**Comment by mwetter** [comment]
I don't know, you will need to test it. BuildingsPy always runs from a mos script so that we can set parameters and other flags.

**Comment by adbuerger** [comment]
If I run the model from a script with the command simulateModel(start=“0“, stop= …), the flag is still being ignored. The simulation stores every event in the output file, which leads to huge output files until in my case, the error „output file too large“ comes up. But if I simulate the model with the command simulate(), it works.

The problem here is, that simulate() always creates an output file named dsres.mat, that gets overwritten after a second simulation is running. I have not found a way to change the names of those output files. So if you want to run more than one model successively you have to add a command into the script, to copy those files after each simulation to another place.

So, in either case, it doesn’t seem to be a problem from buildingspy, and thank you for your help!

**Comment by thorade** [comment]
@adbuerger Closing, as you say it is not a BuilingsPy problem.
If you find a solution to your problem it would be nice if you could post it here, it might help someone in the future.
