### ISSUE TITLE
temporarily enable the depracated travis images

### ISSUE THREAD

**Issue by mwetter** [lbl-srg/BuildingsPy#167]
This branch is to enable the deprecated travis images until the root cause for the failure with the new images is solved. See also
https://blog.travis-ci.com/2017-06-21-trusty-updates-2017-Q2-launch

**Comment by thorade** [comment]
related: https://github.com/travis-ci/travis-ci/issues/7995

**Comment by thorade** [comment]
The issue on the Travis side has been closed, so I guess this has to be solved on the BuildingsPy side. 
Somehow use the UID to change the owner or add more rights to avoid the permission denied error.

**Comment by mwetter** [comment]
@thorade @Mathadon 
Do you know why 
https://travis-ci.org/lbl-srg/BuildingsPy/jobs/392520457
fails for Python 2.7.14 (and also for 2.7.12) but not for 3.5? The tests pass on my Ubuntu with Python 2.7.12, and they also pass with the old deprecated travis image.

**Comment by thorade** [comment]
Also, module not found seems a strange error. I have restarted the jobs, just to be sure it was not a temporary travis thing. And I added one commit increasing the clone depth from 3 to 5.

Travis default clone depth is 50, so going to 3 or 5 does not save that much time. What does save some seconds is to not use full clone in the one test/example, when cloning from python.
https://github.com/lbl-srg/BuildingsPy/search?q=depth&unscoped_q=depth

**Comment by thorade** [comment]
Third idea: Might be a difference between system wide packages and virtual env packages (not sure about the name really). Maybe the Python version has to match exactly? I think Travis uses 2.7.6 by default.
https://docs.travis-ci.com/user/languages/python#Travis-CI-Uses-Isolated-virtualenvs

**Comment by thorade** [comment]
@mwetter Sorry for adding commits to your branch, I thought I try one thing using the web interface, then it became multiple commits, but they did not work, so can you just reset the branch to your last commit? Or I do that, but later, I don't have a git client right now.

**Comment by mwetter** [comment]
@thorade Thanks for your trials. Note that travis uses by default:
```
$ python --version
Python 2.7.14
```
I set this to 2.7.12 in one of the test without any improvement.

**Comment by thorade** [comment]
This is strange, some of the unittests work, some fail with "module not found"
unittest discovery can be made more verbose by:
```
python -m unittest discover -v buildingspy/tests
```
I do not see the difference between tests that work and tests that fail.

https://travis-ci.org/lbl-srg/BuildingsPy/jobs/392820969

**Comment by thorade** [comment]
Just to be sure, I just re-enabled the deprecated image and the same tests still fail on 2.7 (on 3.5 it works):
https://travis-ci.org/lbl-srg/BuildingsPy/builds/392828385

**Comment by thorade** [comment]
@mwetter Did you change capitalization of some directories or filenames?

**Comment by mwetter** [comment]
@thorade I did not change the capitalization. I wonder if the most promising path would be to fix the "unclosed file" warnings that show on python 3.5 (https://travis-ci.org/lbl-srg/BuildingsPy/jobs/392828387) and see if this causes some side effect on 2.7 that breaks the tests.

**Comment by thorade** [comment]
These warnings in 3.5 have been there for a long time, and the recommended way to handle is is to use 
`with open() as fil` instead of `fil = open() … fil.close()`. I tried to add that in several places, and some warnings disappeared, but did not find all and then gave up.

**Comment by thorade** [comment]
I still do not see the difference between the tests that work and the tests that fail, but somehow it seems to be related to the `sys.path` being different on Travis than locally.
https://stackoverflow.com/a/3646370/874701
https://stackoverflow.com/a/35246863/874701
