### ISSUE TITLE
simulate() fails if startup-folder is set in Dymola

### ISSUE THREAD

**Issue by mariusoei** [lbl-srg/BuildingsPy#197]
Hey there,

I believe I found a bug when using BuildingsPy with Dymola 2018 (x86).
Running a very simple example worked well at first.

I was tired of changing my working directory every time I used Dymola though, so I saved my working directory as the startup directory (File -> Working Directory -> Use as Startup Directory).
When I tried using BuildingsPy again, it failed.
On startup (I activated the GUI) it fails to run the mos-File created by BuildingsPy.

In the Simulator method `_simulate`, Dymola is run with the parameter ".\run.mos".
Dymola cannot find this file though, because the working directory is not the one it was called from (the temporary directory created by `simulate()`) but the one I set before as the startup directory. 

I'm not sure how to fix this, but it works if you provide the full path to the mos-file when starting Dymola instead of the relative path.

Best,
Marius

**Comment by mwetter** [comment]
If the full path to `run.mos` is provided to Dymola, then Dymola probably works (as you state), but BuildingsPy would not find the output file of Dymola (such as the `.mat` file), as Dymola would write it in its working directory which is not known to BuildingsPy. Hence, it is not clear how BuildingsPy could deal in a robust way with the situation of a user overwriting the working directory from inside Dymola.

**Comment by mariusoei** [comment]
Hi Michael,

thanks for your answer.
I'm new to Dymola, so I don't really know a lot about it yet.
Maybe you could read the working directory from the settings file or
provide the full path to the mos-file and add a cd-command to the script?

Best,
Marius

Michael Wetter <notifications@github.com> schrieb am Mo., 26. März 2018,
19:58:

**Comment by mariusoei** [comment]
The problem can be solved (at least for me on Windows) by changing 2 lines in Simulator.py:

1. Uncomment the cd-command in `_get_dymola_commands` on line 360:
```
s = """
// File autogenerated by _get_dymola_commands
// Do not edit.
cd("{working_directory}");
Modelica.Utilities.Files.remove("{log_file}");
openModel("package.mo");
OutputCPUtime:=true;
""".format(working_directory=working_directory,
           log_file=log_file)
```
2. Change line 773 to `mo_fil = mosFile`. However, the comment above says 
```
# Remove the working directory from the mosFile name.
# This is needed for example if the simulation is run in a docker,
# which may have a different file structure than the host.
mo_fil = mosFile.replace(directory, ".") 
```

I don't know what this refers to or what a docker is, but maybe there's a way to distinguish between a regular Windows computer where we can use the absolute file path and the case where we need the relative path.
I'm not filing a pull request because it seems like this is not a general solution.

Best,
Marius
