### ISSUE TITLE
buildingspy consistency

### ISSUE THREAD

**Issue by Mathadon** [lbl-srg/BuildingsPy#198]
I'm going through the buildingspy code to make some changes. Something got my attention in https://github.com/lbl-srg/BuildingsPy/blob/master/buildingspy/development/regressiontest.py .
See first and last line.

```
roo_pac = root_package if root_package is not None else os.path.join(
            self._libHome, 'Resources', 'Scripts', 'Dymola')
        for root, _, files in os.walk(roo_pac):
            for mosFil in files:
                # Exclude the conversion scripts and also backup copies
                # which have the extensions .mos~ if they are generated from emacs
                if mosFil.endswith('.mos') and (
                    not mosFil.startswith(
                        "Convert" + self.getLibraryName())):
                    matFil = ""
                    dat = {
                        'ScriptFile': os.path.join(root[len(os.path.join(self._libHome, 'Resources', 'Scripts', 'Dymola')) + 1:],
                                                   mosFil),
```
should the last line not be 
```
dat = {
                        'ScriptFile': os.path.join(root[len(roo_pac) + 1:],mosFil),
```
?

**Comment by Mathadon** [comment]
@mwetter the point is that `roo_pac` sets a default value of `os.path.join(self._libHome, 'Resources', 'Scripts', 'Dymola')` if `root_package` is not defined. But then at the last line, you don't use `roo_pac`. The default value is used instead. To me it looks like this can lead to an inconsistency in the paths when using `root_package `?

**Comment by mwetter** [comment]
@Mathadon : I don't see the consistency. Did you test the value for `dat['ScriptFile']` for either setting of `root_package`? In both cases, `dat['ScriptFile']` is the name of the `*.mos` file, with the full directory after `Resources/Scripts/Dymola`

**Comment by Mathadon** [comment]
I figured it out. I made a misinterpretation of the code..
