### ISSUE TITLE
add files to be excluded from merger.merge()

### ISSUE THREAD

**Issue by mwetter** [lbl-srg/BuildingsPy#199]
Calling `merger.merge()` also merges various files such as all `.mat` files. This issue is to change the merge function so that certain file patterns can be filtered out from the merge.

**Comment by thorade** [comment]
The workaround I used in the past:
Before merging, call `git clean -ndx` (dry run), then `git clean -fdx` (force remove) to delete all untracked files.

**Comment by thorade** [comment]
Looking at the list of excluded files, it reminds me of the files listed in gitignore.
If the list of excluded files would be read from a file, one could just reuse the gitignore file (or have another BPignore file).

**Comment by mwetter** [comment]
Reading `.gitignore` and a `.BuildingsPyIgnore` would indeed be a cleaner solution in the long run.
