### ISSUE TITLE
Run code validation with pep8

### ISSUE THREAD

**Issue by mwetter** [lbl-srg/BuildingsPy#20]
Add pep8 to makefile, such as

```
pep8 development/validator.py
```

and clean up code.
See also http://docs.python-guide.org/en/latest/writing/style/

**Comment by thorade** [comment]
Maybe integrate pep8 or flake8 into Travis?
https://www.caktusgroup.com/blog/2015/08/15/making-clean-code-part-your-build-process/

**Comment by mwetter** [comment]
@thorade Adding `autopep8` to the tests seems a good idea to keep the code clean.
