### ISSUE TITLE
slow parsing using Modelica.Utilities.Strings.Count

### ISSUE THREAD

**Issue by Mathadon** [lbl-srg/BuildingsPy#203]
BuildingsPy relies on the use of `Modelica.Utilities.Strings.Count` for counting the number of occurrences of specific substrings in the translation log. This implementation seems quite inefficient, which is a problem for large models that have a translation log of ~100 kB. 

To illustrate the problem:
For a specific file that I am working on, executing `iJac=sum(Modelica.Utilities.Strings.count(lines, "Number of numerical Jacobians: 0"));` takes about one second. 

Using python
```
with open("IDEAS.Examples.PPD12.Ventilation.translation.log") as f:
	test=0
	for lin in f.readlines():
		test+=lin.count("Number of numerical Jacobians: 0")
	print test
```
this takes 0.01 seconds. When I modify the file such that all newlines are removed, then the computation time increases to 13s for Modelica and to 0.01 seconds in python.

Longer lines are thus treated less efficiently, which is problematic in our models since we often get long output in the form of

```
The model has

  33036+2*valBed1.val.filter.order+valBat2.val.filter.order+valBat2.val.filter.order  +valBat1.val.filter.order+valBat1.val.filter.order+valBed2.val.filter.order+  valBed2.val.filter.order+valBed3.val.filter.order+valBed3.val.filter.order+  valGnd.val.filter.order+valGnd.val.filter.order+max(com1.layMul.monLay[1].monLayDyn.nStaMin,   2)+(if com1.layMul.monLay[1].monLayDyn.addRes_b then max(com1.layMul.monLay[1].monLayDyn.nStaMin,   2) else max(max(com1.layMul.monLay[1].monLayDyn.nStaMin, 2)-1, 1))+max(  com1.layMul.monLay[2].monLayDyn.nStaMin, 2)+(if com1.layMul.monLay[2].monLayDyn.addRes_b   then max(com1.layMul.monLay[2].monLayDyn.nStaMin, 2) else max(max(  com1.layMul.monLay[2].monLayDyn.nStaMin, 2)-1, 1))+max(out1.layMul.monLay[1].monLayDyn.nStaMin,   5)+(if out1.layMul.monLay[1].monLayDyn.addRes_b then max(out1.layMul.monLay[1].monLayDyn.nStaMin,   5) else max(max(out1.layMul.monLay[1].monLayDyn.nStaMin, 5)-1, 1))+max(  out1.layMul.monLay[2].monLayDyn.nStaMin, 2)+(if out1.layMul.monLay[2].monLayDyn.addRes_b   then max(out1.layMul.monLay[2].monLayDyn.nStaMin, 2) else max(max(  out1.layMul.monLay[2].monLayDyn.nStaMin, 2)-1, 1))+max(cei2.layMul.monLay[1].monLayDyn.nStaMin,   2)+(if cei2.layMul.monLay[1].monLayDyn.addRes_b then max(cei2.layMul.monLay[1].monLayDyn.nStaMin,   2) else max
...
...
scalar equations.
```

Looking at the Modelica code, this may be caused by the implementation of `Find()`, which creates a substring of the checked line and then verifies whether the substring and checked string are equal. This is clearly not the most efficient implementation and it causes a lot of overhead to allocate memory and copy strings.

If we fix this then the unit tests may complete a lot faster, but I'm not sure what is the most appropriate way:
1) Get MSL to fix this (propose a new implementation for `Find()`).
2) Implement our own function and include it in Buildingspy. I think that this would require the unit test script to load an additional package that includes the new function.
3) Do the post-processing of the log file directly in python.

I think we should do 3)?

Edit: I removed the occurrences of `Count()` from buildingspy, which reduced the unit test time for my model from 18m to 3.5m. The other unit tests are not affected as much.

**Comment by thorade** [comment]
I think we should also file an issue with the MSL.

**Comment by Mathadon** [comment]
This is still a problem for us. Unit tests are timing out (50m) on just four example models.

I think it would make sense to implement a function like `startsWith` instead of `find` since that removes most of the overhead.

Function body could be like

```Modelica
function startsWith "Check whether a string starts with another string"
  extends Modelica.Icons.Function;
  input String string "String that is analyzed";
  input String searchString "String that is searched for in string";
  input Integer startIndex(min=1)=1 "Start search at index startIndex";
  input Boolean caseSensitive=true
    "= false, if lower and upper case are ignored for the search";
   output Boolean res;
protected 
  Integer lengthSearchString = length(searchString);
  Integer len = lengthSearchString-1;
  Integer i = startIndex;
  Integer i_max = length(string) - lengthSearchString + 1;
algorithm 
     if isEqual(substring(string,0,len),
                searchString, caseSensitive) then
        res:=true;
     else
        res:=false;
     end if;
end startsWith;
```
the question is where we can put it.. I suppose BuildingsPy can only rely on functions that are in MSL?

Would it be an option to parse the translation log file directly in python instead of using these Modelica functions?

**Comment by mwetter** [comment]
@Mathadon : Parsing the log file in python is probably the best approach. Can you provide an implementation?
