### ISSUE TITLE
Update autopep8

### ISSUE THREAD

**Issue by mwetter** [lbl-srg/BuildingsPy#237]
This issue is to remove the `--aggressive` flags as `autopep8` now adds various literal string signs, see for example https://travis-ci.org/lbl-srg/BuildingsPy/jobs/474643741#L736

**Comment by thorade** [comment]
The addition of r"" only happens for strings contatining regex, or certain escape sequences.
autopep8 uses pycodestyle, this issue seems to be related:
https://github.com/PyCQA/pycodestyle/issues/766
So maybe having the r is the preferred way?
