### ISSUE TITLE
Funnel integration and diagnostics reports

### ISSUE THREAD

**Issue by AntoineGautier** [lbl-srg/BuildingsPy#245]
- [x] Switch from current comparison algorithm to funnel by default: keep legacy algorithm as an option.
- [x] Implement an HTML diagnostics report (at library level) similar to [(https://jenkins.jmodelica.org/job/PlanarMechanics-Compliance-Simulation/lastSuccessfulBuild/artifact/diag/index.html](https://jenkins.jmodelica.org/job/PlanarMechanics-Compliance-Simulation/lastSuccessfulBuild/artifact/diag/index.html)
- [x] Implement an HTML plot report (at unit test level) similar to [https://jenkins.jmodelica.org/job/PlanarMechanics-Compliance-Simulation/lastSuccessfulBuild/artifact/diag/PlanarMechanics_Examples_KinematicLoop_DynamicStateSelection_result_report.html](https://jenkins.jmodelica.org/job/PlanarMechanics-Compliance-Simulation/lastSuccessfulBuild/artifact/diag/PlanarMechanics_Examples_KinematicLoop_DynamicStateSelection_result_report.html)

**Comment by MichaMans** [comment]
@AntoineGautier 
Hi Antoine, greetings from RWTH Aachen, Germany. I found this issue by accident, but it directly took my attention. I was kind of forced to directly test your WIP. It looks already great! Thank you for your effort on that! Nevertheless i was wondering about a thing which i want to share and which we might discuss:
- Currently you are serving the html report via the funnel python binding right? Do you see a possibility to save the report.html and plot.html file in the funnel_comp directory in the tested library, which can then be served with whatever static webserver you want? This would be a great option to directly integrate these html files into the library testing workflows like travis or gitlab-ci etc.

**Comment by AntoineGautier** [comment]
@MichaMans 
Definitely possible as far as the HTML files are concerned. At the moment the HTML content is passed to the browser as a stream in response to a request. It could either be written in a file to be served by whatever means (allowing JS code to be executed). I will allow for this option.
However we have not yet decided what was the best way to store the actual results of the funnel comparison. At the moment they are stored locally in the directory `funnel_comp`. We are discussing with Michael about the best strategy to store them remotely (LBL server or third party) while avoiding data redundancies. Hope to discuss it with you too in Aachen next week.
Thanks a lot for your contribution at this early stage.

**Comment by AntoineGautier** [comment]
- [ ] Allow for report and plot HTML to be stored into static file
- [ ] Remote hosting of `funnel` comparison results and integration into CI workflows
