### ISSUE TITLE
Gitpython version

### ISSUE THREAD

**Issue by milicag** [lbl-srg/BuildingsPy#295]
A [travis test](https://travis-ci.org/lbl-srg/modelica-buildings/jobs/584642837) failed with:

```
ERROR: Package 'GitPython' requires a different Python: 2.7.14 not in '>=3.0, !=3.0.*, !=3.1.*, !=3.2.*, !=3.3.*'

The command "pip install git+https://github.com/lbl-srg/BuildingsPy@master" failed and exited with 1 during .
```

That issue seems related to a change in gitpython see https://github.com/gitpython-developers/GitPython/issues/897

**Comment by milicag** [comment]
@AntoineGautier Please see this issue. Thanks!

**Comment by AntoineGautier** [comment]
It seems like a bug in Travis Python 2 environment.
Running
`pip install git+https://github.com/lbl-srg/BuildingsPy@master`
in a local Python 2 environment logically installs a Python 2 compatible version of gitpython (2.1.14).
Until Travis fixes its Python 2 environment we can [conditionally specify the version of gitpython](https://setuptools.readthedocs.io/en/latest/setuptools.html#declaring-platform-specific-dependencies) installed by buildingspy.

**Comment by AntoineGautier** [comment]
@milicag Could you try to run the Travis test again? I noticed that the original one is 17 days old and more recent PR in Buildings do not seem to have that issue e.g. [https://travis-ci.org/lbl-srg/modelica-buildings/jobs/590495934](https://travis-ci.org/lbl-srg/modelica-buildings/jobs/590495934) which installs a proper version of gitpython (2.1.14).

**Comment by milicag** [comment]
Tests run fine after rerunning.
