### ISSUE TITLE
JModelica unit tests don't work with Python3

### ISSUE THREAD

**Issue by mwetter** [lbl-srg/BuildingsPy#314]
Running the unit tests of JModelica with Python3 gives the following error:
```
/tmp/tmp-Buildings-24-2cbKPe/run.py in <module>
    108 if __name__=="__main__":
    109 
--> 110     run_Buildings_Air_Systems_SingleZone_VAV_Examples_ChillerDXHeatingEconomizer()
    111 
    112     run_Buildings_BoundaryConditions_WeatherData_Validation_ThreeYears_usingTwoYearData()

/tmp/tmp-Buildings-24-2cbKPe/run.py in run_Buildings_Air_Systems_SingleZone_VAV_Examples_ChillerDXHeatingEconomizer()
      2 def run_Buildings_Air_Systems_SingleZone_VAV_Examples_ChillerDXHeatingEconomizer():
      3     import Buildings_Air_Systems_SingleZone_VAV_Examples_ChillerDXHeatingEconomizer as m
----> 4     m.run()
      5 
      6 def run_Buildings_BoundaryConditions_WeatherData_Validation_ThreeYears_usingTwoYearData():

/tmp/tmp-Buildings-24-2cbKPe/Buildings_Air_Systems_SingleZone_VAV_Examples_ChillerDXHeatingEconomizer.py in run()
    214 
    215     except Exception as e:
--> 216         result["translation"]["exception"] = "{}: {}".format(type(e).__name__, e.message)
    217         result["translation"]["traceback"] = traceback.format_exc()
    218 

AttributeError: 'KeyError' object has no attribute 'message'
```

**Comment by mwetter** [comment]
After https://github.com/lbl-srg/BuildingsPy/commit/fb1ba7d7aa05a200946c7bde6a48ecdb0c00d8a0 I get a new error with oct. To reproduce, uncomment in `bin/runUnitTest.py` the line    
```
ut.deleteTemporaryDirectories(False)
```
and run 
```
../bin/runUnitTests.py -s Buildings.Controls.Continuous -t jmodelica
```
Then, go to the temporary folder that has a model and run
```
jm_ipython.sh Buildings_Controls_Continuous_Examples_LimPIDWithReset.py
cat Buildings_Controls_Continuous_Examples_LimPIDWithReset_run.json
```
This shows the error
```
"exception": "TypeError: a bytes-like object is required, not 'str'",
```

**Comment by JayHuLBL** [comment]
The previous exception after the implementation of fb1ba7d:
```
"exception": "TypeError: a bytes-like object is required, not 'str'",
```
was due to that python3 expect bytes-like object in following line:
```
if not char or self.escape_char in char:
```
by converting string object (`self.escape_char`)  to byte-obejct `str.encode(self.escape_char)` solves the issue. 

We'd also need to convert the byte-object `char` in `self.capturedtext += char` to string: `self.capturedtext += str(char, 'utf-8')`.

**Comment by mwetter** [comment]
@JayHuLBL : Thanks, can you please make a pull request once you finished the testing.

**Comment by JayHuLBL** [comment]
Further updates:
- [x] in `buildingspy/io/postprocess.py`, line 
```tGrid = np.linspace(0, tMax - increment, num=round(tMax / increment))``` fails with error: ```TypeError: 'numpy.float64' object cannot be interpreted as an index```. As for the new version of numpy (>1.11.0), `np.round( )` creates a float, not integer. By changing it to `np.round( ).astype(np.int)` will ensure integer value. See [here](https://github.com/rbgirshick/py-faster-rcnn/issues/481).
- [x] also in file `buildingspy/io/postprocess.py`, follow line fails:
```
Plotter.boxplot(t, y, increment=0.5, nIncrement=2 * 24,
                         notch=0, sym='b+', vert=1, whis=1.5,
                         positions=None, widths=None, patch_artist=False, bootstrap=None, hold=None)
```
The keyword `hold` is deprecated. See [Matplotlib 2.2.x](https://matplotlib.org/api/pyplot_api.html) and [Matplotlib 3.x](https://matplotlib.org/3.1.1/api/_as_gen/matplotlib.pyplot.boxplot.html).

**Comment by mwetter** [comment]
Fixed on master now.
