### ISSUE TITLE
installation not working for 2.1 due to pyfunnel

### ISSUE THREAD

**Issue by Mathadon** [lbl-srg/BuildingsPy#371]
I'm getting 
```
Installed /usr/local/lib/python3.7/site-packages/buildingspy-2.1.0-py3.7.egg
Processing dependencies for buildingspy==2.1.0
Searching for pyfunnel@ git+https://github.com/lbl-srg/funnel.git@v0.1.0
Reading https://pypi.org/simple/pyfunnel/
Couldn't find index page for 'pyfunnel' (maybe misspelled?)
Scanning index of all packages (this may take a while)
Reading https://pypi.org/simple/
No local packages or working download links found for pyfunnel@ git+https://github.com/lbl-srg/funnel.git@v0.1.0
error: Could not find suitable distribution for Requirement.parse('pyfunnel@ git+https://github.com/lbl-srg/funnel.git@v0.1.0')
```

when running `sudo python3 setup.py install` using python3.7 on OSX.

**Comment by AntoineGautier** [comment]
Indeed, installing without pip requires an additional `dependency_links` in `setup.py`.
However, if providing the link through `dependency_links`, installations with pip (fairly more common I would assume) will fail (the former flag `--process-dependency-links` is now deprecated).
The only syntax that I found working for both pip and setuptools installations requires the following redundancy.
```
install_requires=[
        'pyfunnel@git+https://github.com/lbl-srg/funnel.git/@v0.1.0#egg=pyfunnel',
    ],
dependency_links=[
        'git+https://github.com/lbl-srg/funnel.git/@v0.1.0#egg=pyfunnel',
    ],
```
So either we go with this syntax or we make installation from pip a requirement for the package. A last option would be to publish pyfunnel on PyPI.

**Comment by Mathadon** [comment]
I'll leave it up to LBL to decide on how to solve this :)
