### ISSUE TITLE
support for OpenModelica?

### ISSUE THREAD

**Issue by epaulson** [lbl-srg/BuildingsPy#426]
I'm super-new to Modelica, and thus far have only really figured out what the "Hello World" example in OpenModelica is telling me.

Does BuildingsPy support OpenModelica for running simulations, or is it only Dymola and JModelica? (Both of which I can't find a price for anywhere - I suspect they're in the category of "If you have to ask you can't afford it" software prices)

Thanks!

**Comment by mwetter** [comment]
OpenModelica is not yet supported with the Buildings library and with BuildingsPy, but work is ongoing.

**Comment by bilderbuchi** [comment]
I'm confused - if OpenModelica support is planned and actually work-in-progress (great news!), but not completed yet, why close this issue? Would you not close this when OM support has arrived?
Is there a place where that work can be tracked/followed? I did not find any commits or PRs after 2017 that mention Openmodelica.

**Comment by mwetter** [comment]
@bilderbuchi : See https://simulationresearch.lbl.gov/modelica/environments.html for a link to open issues. Most of them are dealt with on the OpenModelica dev page, and some on the Modelica Buildings Library github site if there are issues in the library to be resolved.

**Comment by bilderbuchi** [comment]
Ah Thanks for that link. So if I interpret the mostly green graphs correctly, most things should work with OM already (just not officislly supported), and @epaulson is probably best off trying with some examples and maybe cross-referencing the models he wants to use with that OM test list?
