### ISSUE TITLE
Bug in regressiontest under windows

### ISSUE THREAD

**Issue by damienpicard** [lbl-srg/BuildingsPy#47]
the file `regressiontest` gives an error under Windows due to the use of json library: all the path needs to be given with double escape (`\\`) or forward slash `/`.  Otherwise its give an *escape error*.

There is also an error with loading the file *statistics.json*. The path should also only contain double escape. I do not understand why but I could not replace the single escape between `..\Temp\tmp...` to a double one using the command replace. I had to use `replace("Temp\tmp","Temp\\tmp")`.

I will issue a pull request which works for me in Windows. I do not, however, if this will be compatible with Linux system.

I also had to use `chech_html=False` as *libtidy* also gave some errors. I have tried many things but so far unsuccesfully.

**Comment by mwetter** [comment]
Thanks. I merged it to the master.
I don't know what issues you have with libtidy. I tested it again on Ubuntu and on OSX, and both installations work.
On OSX, I had to run `sudo pip install pytidylib` to install libtidy.

**Comment by damienpicard** [comment]
The installation of pytidylib seems to work, but I get the following error when `Tester(check_html=True)`:

```
*** Warning: Regression tests are only run for 'IDEAS.Fluid.HeatExchangers.RadiantSlab.Examples'.
Using  1  of  4  processors to run unit tests.
Number of models   :  392
          blocks   :  111
          functions:  87
Traceback (most recent call last):
  File "RunUnitTestsDaP.py", line 34, in <module>
    rt.run()
  File "c:\Anaconda\lib\site-packages\buildingspy-1.4.0-py2.7.egg\buildingspy\development\regressiontest.py", line 2071,
 in run
    errMsg = val.validateHTMLInPackage(self._libHome)
  File "c:\Anaconda\lib\site-packages\buildingspy-1.4.0-py2.7.egg\buildingspy\development\validator.py", line 63, in val
idateHTMLInPackage
    err = self._validateHTML(moFulNam)[1]
  File "c:\Anaconda\lib\site-packages\buildingspy-1.4.0-py2.7.egg\buildingspy\development\validator.py", line 133, in _v
alidateHTML
    'wrap': 72})
  File "build\bdist.win32\egg\tidylib\__init__.py", line 134, in tidy_document
ValueError: Procedure probably called with too many arguments (8 bytes in excess)
```

**Comment by mwetter** [comment]
@damienpicard 
I don't see any bug in `buildingspy` that could cause your issue. Can you try to run the small example on 
http://pythonhosted.org/pytidylib/#small-example-of-use
If this works, please also try with the options
```
options={'numeric-entities': 1,
                'output-html': 1,
                'alt-text': '',
                'wrap': 72}
```
which is what is used in `buildingspy`.

**Comment by damienpicard** [comment]
@mwetter I have indeed some problems with this example too:

```
$ python
Python 2.7.10 |Anaconda 2.3.0 (32-bit)| (default, May 28 2015, 17:02:00) [MSC v.1500 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.
Anaconda is brought to you by Continuum Analytics.
Please check out: http://continuum.io/thanks and https://binstar.org
>>> from tidylib import tidy_document
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "build\bdist.win32\egg\tidylib\__init__.py", line 68, in <module>
OSError: Could not load libtidy using any of these names: libtidy,libtidy.so,libtidy-0.99.so.0,cygtidy-0-99-0,tidylib,li
btidy.dylib,tidy
```

The problem seems to be with the `tidylib.dll`. In the installation instructions, they mention that you need both 'tidylib.dll' and having install 'pytidylib'. I'll have a look in the future if I can fix this problem.

**Comment by mwetter** [comment]
@damienpicard 
You may need to install tidylib manually as it looks like it requires resources that are not installed with `pip`.
I verified the installer of BuildingsPy and it works fine on Linux, and there seems no option that is specifically for Windows versus Linux.

I suggest you try to run these lines manually to verify your tidylib installation:
```
from tidylib import tidy_document
document, errors = tidy_document('''<p>f&otilde;o <img src="bar.jpg">''',
    options={'numeric-entities':1})
print document
print errors
```

**Comment by damienpicard** [comment]
This simple example seems to work fine:

```
>>> from tidylib import tidy_document
>>> document, errors = tidy_document('''<p>f&otilde;o <img src="bar.jpg">''',
...     options={'numeric-entities':1})
>>> print document
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01//EN">
<html>
  <head>
    <title></title>
  </head>
  <body>
    <p>
      f&#245;o <img src="bar.jpg" alt="">
    </p>
  </body>
</html>

>>> print errors
line 1 column 1 - Warning: missing <!DOCTYPE> declaration
line 1 column 1 - Warning: inserting implicit <body>
line 1 column 1 - Warning: inserting missing 'title' element
line 1 column 15 - Warning: <img> lacks "alt" attribute
```

**Comment by damienpicard** [comment]
@mwetter my bad: on Windows you indeed need to install tidylib manually. By simply download the tidylib.dll and put in your system path it works. My mistake was that I put it in the folder I was working in for the unit test, but as they are runt in another (temperory) folder, the .dll was not found.

This is now working properly.

Maybe the documentation could specify these steps?

**Comment by raghavm89** [comment]
how to make pytidylib run on linux, it is working fine for osx but failing in linux with same OS error

**Comment by mwetter** [comment]
It should suffice to install https://packages.ubuntu.com/bionic/tidy
