### ISSUE TITLE
Custom location for MODELICAPATH for OM

### ISSUE THREAD

**Issue by Mathadon** [lbl-srg/BuildingsPy#488]
I'm trying to run the unit tests using OM. The omc call fails since omc apparently does not use the MODELICAPATH that I have set in OMEdit. However, manually adding `setModelicaPath()` in the autogenerated .mos file does the trick. Can I make a pull request for adding this overwrite as an option or should I deal with this in a different way?

**Comment by mwetter** [comment]
Do you set the path like here?
https://github.com/lbl-srg/modelica-buildings/blob/a0b13bd2905603c1acbe525e8d8998d5b2b86439/Buildings/Resources/Scripts/travis/omc/omc#L94

**Comment by Mathadon** [comment]
Works! Muchos gracias :)
