### ISSUE TITLE
integrate simulationCompare script

### ISSUE THREAD

**Issue by mwetter** [lbl-srg/BuildingsPy#492]
This issue is to integrate the script that compares translation and simulation performance across branches or tools.

**Comment by JayHuLBL** [comment]
@mwetter 
Through commit [1ae12a0](https://github.com/lbl-srg/BuildingsPy/commit/1ae12a08501dd8feed840f3d80bd5a39e1fad8f4), the failed models will be successfully listed at the top of the html output. These models then are no longer listed in the tables below.
