### ISSUE TITLE
also install dependencies

### ISSUE THREAD

**Issue by thorade** [lbl-srg/BuildingsPy#51]
After installing BuildingsPy using `pip install -U buildingspy` I got a warning because `tidylib` was missing, so I had to run `pip install -U pytidylib` (because that package contains `tidylib`). 

Can you specify depencies on PyPi, so that `pip` will automatically install `pytidylib` when installing `buildingspy`? 
Alternatively, one could just add a notice to the [BuildingsPy installation instructions](http://simulationresearch.lbl.gov/modelica/buildingspy/install.html).

Of course, one also has to install the `tidylib` executable from http://tidy.sourceforge.net/

**Comment by thorade** [comment]
The `setup.py` already contains the line

```python
install_requires = ["pytidylib"],
```
since May 2014, but BuildingsPy was lat updated on PyPi in February 2014:
https://pypi.python.org/pypi/buildingspy

So, to fix this issue you would just have to push a new version to PyPi.
This issue can be closed whenever you want, before or after pushing the update.

**Comment by bilderbuchi** [comment]
It seems this can be closed.

**Comment by thorade** [comment]
https://github.com/lbl-srg/BuildingsPy/blob/master/setup.py#L19

**Comment by bilderbuchi** [comment]
Ah, didn't see that, I was purely going by the pypi version. No, I don't know how to fix it.

**Comment by mwetter** [comment]
@thorade @bilderbuchi 
I have not found a fix either which is why I commented the line so that pip runs without an error.

**Comment by thorade** [comment]
There seems to be an alternative way to inform pip about the dependencies: a `requirements.txt` file:
https://pip.readthedocs.io/en/1.1/requirements.html
Not sure though whether that would solve the problem.

**Comment by thorade** [comment]
Note:
If you include more than one requirement in a string, each requirement must begin on a new line.
http://setuptools.readthedocs.io/en/latest/setuptools.html#declaring-dependencies
Using double or single quotes should not matter.

**Comment by mwetter** [comment]
@thorade We already have one requirement only per line.

**Comment by thorade** [comment]
Yes, it was just an explanation / note for future me why the fix worked. My PR changed it from single to double quotes and from one single line to multiple lines. Sorry for the confusion
