### ISSUE TITLE
Update for the BuildingsPy example

### ISSUE THREAD

**Issue by gitsdfawfevi** [lbl-srg/BuildingsPy#519]
The model `Buildings.Controls.Continuous.Examples.PIDHysteresis.mo` used in the example:

https://simulationresearch.lbl.gov/modelica/buildingspy/examples.html

is no longer present in the current modelica-buildings. The example should be updated so that a test for users does not fail.

**Comment by mwetter** [comment]
This is corrected on the master branch.
