### ISSUE TITLE
merger.py expects lib name and dir name to be different

### ISSUE THREAD

**Issue by thorade** [lbl-srg/BuildingsPy#55]
Line 159 of merger.py reads (or closeby)
```python
roo = self._target_home.split(self._new_library_name)[0]
```
Not 100% sure, but I believe this is causing problems if the library name and the above directory name are identical, e.g. a path to the main package.mo like this one
```
C:\Users\mthorade\Documents\Dymola\BuildingSystems\BuildingSystems\package.mo
```
will be split at the wrong location.
Correct me if I am wrong and feel free to close this as won't fix, as there is an easy workaround (just rename the directory).

**Comment by mwetter** [comment]
Can you please try again with the master. This should have been fixed in
https://github.com/lbl-srg/BuildingsPy/commit/4d7887a89368afcdef7557c3c107ab0b376f755d

**Comment by thorade** [comment]
OK, I was using the latest master in iea-annex60/BuiildingsPy (which is currently 11 commits ahead and 13 behind). With the latest master from lbl-srg I get a fixme***** warning and the script seems to work. Closing this issue.
Should I use the iea-annex60 version or the lbl-srg version in the future? Will the fork be re-integrated later?

**Comment by mwetter** [comment]
@thorade The Annex60 fork will be integrated with the master on lbl-srg. Usually lbl-srg is ahead in terms of development.
