### ISSUE TITLE
Add options for more than one library 

### ISSUE THREAD

**Issue by FWuellhorst** [lbl-srg/BuildingsPy#558]
If you want to test a project with dependencies, e.g., as BESMod, performing regressiontests will not work, as only the library is loaded before simulation. 

Solution:
- [ ] add option to execute another .mos script, e.g. startup.mos which loads multiple libraries
- [ ] add option to add a single package for cases where a .mos to start dymola does not exists.

**Comment by FWuellhorst** [comment]
@mwetter : You are correct, this option is cleaner. I normally don't use the path as I have multiple versions on the same device, but for CI this is fine.

**Comment by mwetter** [comment]
@FWuellhorst : Note that you can have multiple versions on the same device if you use the version number, e.g., safe them as
```
some/directory/MyLibrary 1.0.0
              /MyLibrary 1.1.0
```
and then use the `uses` statement.
