### ISSUE TITLE
no fmi built

### ISSUE THREAD

**Issue by damienpicard** [lbl-srg/BuildingsPy#64]
It seems that the fmi function is not built using the setup.py.

On windows I get an error when calling     `def _check_fmu_statistics(self, ans):` saying that no file `fmi` exists.

**Comment by mwetter** [comment]
@damienpicard 
Can you try again with the version from the master. The entry for the fmi folder was missing in setup.py, which I fixed in 8570cdd

**Comment by damienpicard** [comment]
Your changes fixed the bug. Thank you.
