### ISSUE TITLE
problem using multiple thread under windows

### ISSUE THREAD

**Issue by damienpicard** [lbl-srg/BuildingsPy#65]
I experience problem using rt.setNumberOfThreads() for a higher number than 1.
The error I get is the following: 

![image](https://cloud.githubusercontent.com/assets/2987659/9085630/bebb04cc-3b7e-11e5-9911-cee992cb7990.png)

**Comment by mwetter** [comment]
@damienpicard 
Can you try to replace in `runUnitTest.py` the section
```
if __name__ == '__main__':
    import platform
    batch = False
```
with
```
if __name__ == '__main__':
    import platform
    import multiprocessing
    multiprocessing.freeze_support()
    batch = False
```
See https://docs.python.org/2/library/multiprocessing.html#multiprocessing.freeze_support

**Comment by damienpicard** [comment]
@mwetter I'm not sure what you mean. I can't find in BuildingsPy the file `runUnitTest.py` and in my file `runUnitTestDap.py` I do not use the section
```
if __name__ == '__main__':
    import platform
    batch = False
```

**Comment by mwetter** [comment]
@damienpicard The `if __name__ == '__main__'` is good practice and needed for parallel computing on Windows.
Can you try my suggestion on https://github.com/iea-annex60/modelica-annex60/blob/master/bin/runUnitTests.py and see if this works for you?

**Comment by damienpicard** [comment]
@mwetter the example you suggested run without problems, and this without the adaptation in `__main_` .

By copying the code for IDEAS the problem is solved too...

So I'm not sure what the problem was. If you are interested, here is the code we used:
https://github.com/open-ideas/IDEAS/blob/master/IDEAS/RunUnitTests.py
