### ISSUE TITLE
overwrite reference results when merging

### ISSUE THREAD

**Issue by Mathadon** [lbl-srg/BuildingsPy#66]
Currently reference results are not overwritten when merging files. This is based on code excerpt:

```
# Only copy reference results if no such file exists.
                    # If a reference file already exists, then don't change it.
                    # This requires to replace
                    # the name of the library in names of the result file
                    elif desFil.startswith(ref_res):
                        dir_name = os.path.dirname(desFil)
                        base_name = os.path.basename(desFil)
                        new_file = os.path.join(dir_name,
                                                base_name.replace("Annex60",
                                                                  self._new_library_name))
                        if not os.path.isfile(new_file):
                            copiedFiles.append(new_file)
                            shutil.copy2(srcFil, new_file)
```

I would prefer it if they are updated, or if there would exist a way of overriding this default setting. This way I don't have to go through all changed unit test results for models that are imported from Annex60. Can this be changed?

**Comment by MichaMans** [comment]
@Mathadon quite an old issue here, but since we are starting to integrate ci now for the AixLib, i'm also running into the same problem. I try to create an optional update of the reference results and make a pr. I hopefully ref then all the existing ones so that this could be cleaned up a bit if possible.

**Comment by MichaMans** [comment]
I think, as we implemented an optional solution for that, we can close this
@mwetter thanks for merging!
