### ISSUE TITLE
[ubuntu] buildingspy simulations in linux screens crash when bash is closed 

### ISSUE THREAD

**Issue by kklein1** [lbl-srg/BuildingsPy#86]
Dear developers,
first of all, **thanks so much** for making this awesome tool available to us Dymola users!
I am experiencing a problem though when using buildingspy 1.5.0 to run Dymola 2015FD01 simulations on a linux machine with ubuntu, to which I connect on my local laptop via SSH.

What I want to do is: run multiple Dymola simulations, managed by Python scripts via buildingspy, in linux screens so that I can detach from the screens and disconnect my laptop from the network while the simulations continue to run. This works as long as I keep the bash/login shell open (which of course requires me to stay in the network). However, even after detaching from the screen, closing the bash/login shell will lead to simulation aborts.

The symptoms are as follows:
[case 1] when Dymola is still loading or translating, closing the login shell leads to an immediate crash
[case 2] when Dymola is already simulating, it seems that buildingspy is deleting the temporary directory and I receive the same error message about the missing log file (see below), but Dymola continues to execute the simulation and to write into the already-deleted directory. After the simulation is finished, the Dymola process stops, but buildingspy cannot find the result and log files because the directory is already removed.

So it appears that buildingspy stays connected to something outside the screen, even though Dymola's core simulation process is detached from the bash and continues to run. Do you have an idea what could be the cause of this, or how I could work around this?

Thanks a bunch,
Konstantin

Error message in both cases:
![error1_when_dymol_is_loading translating](https://cloud.githubusercontent.com/assets/19928937/16042521/6fe81506-323b-11e6-9ab3-ff2a9cb41315.png)

**Comment by mwetter** [comment]
@kklein1 
This problem is caused by Dymola because Dymola requires an X Window server during the simulation, even if it is started without the GUI. Hence, when you close your ssh connection, there is no windowing system and Dymola crashes. I don't think there is anything we can do on the Python side.

You can test this by creating a file `~/test/test.mos` that contains
```
simulateModel("Modelica.Blocks.Sources.Clock"); exit();
```
and running from your remote computer
```
mbp-2:test mwetter$ ssh  [your server] "cd test && rm -f dslog.txt && dymola -NoWindow -s test.mos  && cat dslog.txt"
Fatal: QXcbConnection: Could not connect to display 
bash: line 1: 31112 Aborted                 (core dumped) dymola -NoWindow -s test.mos
mbp-2:test mwetter$ ssh -X [your server] "cd test && rm -f dslog.txt && dymola -NoWindow -s test.mos  && cat dslog.txt"
Log-file of program ./dymosim
(generated: Tue Jun 14 15:05:27 2016)

dymosim started
... "dsin.txt" loading (dymosim input file)
... "dsres.mat" creating (simulation result file)

Integration started at T = 0 using integration method DASSL
(DAE multi-step solver (dassl/dasslrt of Petzold modified by Dynasim))
Integration terminated successfully at T = 1
   CPU-time for integration      : 0.00469 seconds
   CPU-time for one GRID interval: 0.00938 milli-seconds
   Number of result points       : 501
   Number of GRID   points       : 501
   Number of (successful) steps  : 19
   Number of F-evaluations       : 37
   Number of Jacobian-evaluations: 18
   Number of (model) time events : 0
   Number of (U) time events     : 0
   Number of state    events     : 0
   Number of step     events     : 0
   Minimum integration stepsize  : 2e-06
   Maximum integration stepsize  : 0.476
   Maximum integration order     : 1
Calling terminal section
... "dsfinal.txt" creating (final states)
^CKilled by signal 2.
mbp-2:test mwetter$ 
```
In the second command, I had to kill the process as Dymola does not seem to release its resources.

**Comment by kklein1** [comment]
Dear Michael,
thanks for your quick and helpful response. Looks like I have to change my toolchain then.
I have realized that only changing parameters/values in the dsin.txt file should work for me as they are not affecting the model structure in my case. So it would be possible to translate/compile the model in a pre-processing step. That should solve the problem for me.
Thanks again!
Konstantin
