### ISSUE TITLE
Python 3 compatibility

### ISSUE THREAD

**Issue by thorade** [lbl-srg/BuildingsPy#94]
It would be nice to make BuildingsPy compatible to Python 3.5+ (without breaking Python 2.7.9+).
The basic idea is that these versions have a sufficient common subset (which is not available in 2.6 or 3.0, e.g. [PEP414](https://www.python.org/dev/peps/pep-0414/)).

There have been Pull Requests #89, #92, #93, #95.
Issue #81 is also related.

Helpful resources:
- https://docs.python.org/3.5/howto/pyporting.html
- http://python-future.org/
- http://python-future.org/compatible_idioms.html

Tasks for makinge the code Py3 compatible:
- [x] Use `print()` function ([PEP 3105](https://www.python.org/dev/peps/pep-3105/)) with [new style `.format`](https://pyformat.info/) syntax ([PEP3101](https://www.python.org/dev/peps/pep-3101/))      
- [x] run [`futurize --stage1`](http://python-future.org/futurize_cheatsheet.html)
- [x] [update `iteritems`](http://python-future.org/compatible_idioms.html#iterating-through-dict-keys-values-items)       
- [x] [update `raw_input`](http://python-future.org/compatible_idioms.html#raw-input)       
- [x] run [`futurize --stage2`](http://python-future.org/futurize_cheatsheet.html#step-2-working-py3-code-that-still-supports-py2)
- [x] [prevent regressions](https://docs.python.org/3/howto/pyporting.html#prevent-compatibility-regressions) by [importing from future](http://python-future.org/imports.html#future-imports)     
- [x] specify encoding of python source files ([PEP263](https://www.python.org/dev/peps/pep-0263/#defining-the-encoding))     
- [x] use [`io.open`](http://python-future.org/compatible_idioms.html#file-io-with-open)  and always [explicitly open in text `t` or binary `b` mode](http://python-future.org/compatible_idioms.html#file)   
- [x] use unicode strings everywhere or add [`unicode_literals`](http://python-future.org/compatible_idioms.html#strings-and-bytes)   
- [x] specify encoding when opening text files, `utf-8` for writing and `utf-8-sig` for [reading](https://docs.python.org/3.6/howto/unicode.html#reading-and-writing-unicode-data)
- [x] run [`futurize --stage2 --all-imports`](http://python-future.org/futurize.html#separating-text-from-bytes) 
- [x] update [setup.py](https://docs.python.org/3.6/howto/pyporting.html#update-your-setup-py-file-to-denote-python-3-compatibility) to mention Python 3

Then, once the code is Py3 compatible:  
- develop new code in Python3 and [import from future](https://docs.python.org/3/howto/pyporting.html#prevent-compatibility-regressions) to make it work with Python 2.7.x. 
 Porting from 3 to 2 is usually very easy, because Py3 is usually stricter than Py2.
- alternatively, when developing new code in Py2, do not forget to import from future to enforce at least some of the Py3 strictness
- use Python 2 with [flags `-3 -Werror`](https://docs.python.org/3/howto/pyporting.html#prevent-compatibility-regressions) at least once
- use Python 3 with [flags `-bb`](https://docs.python.org/3/howto/pyporting.html#use-continuous-integration-to-stay-compatible) at least once

**Comment by thorade** [comment]
intermediate status: 
I can now run HTML check and regressiontest from Python 3.5 on Windows!
`make doccheck` also works on Python 3.5 on Linux, but only if I update the reference results before running it. Cleaning up after doctest has to be done manually.

Next step will be the `from io import open` plus specifying explicitly the text/binary mode.

**Comment by thorade** [comment]
Closing this issue. It works for me on Python 3 and 2.

**Comment by thorade** [comment]
Note: One more thing that might pop up: 
Python does not guarantee dictionaries to be in any particular order! 
This means printing out dictionaries for doctests is fragile:
https://docs.python.org/2/library/doctest.html#warnings
With Python 2 anyhow, the order seems to be always the same, even though it is not guaranteed.

**Comment by dhblum** [comment]
@thorade You may look into ordered dictionaries.
